### ISSUE TITLE
preserving keys (+ types by key) while mapping over objects (R.mapObjIndexed, R.map)

### ISSUE THREAD

**Issue by tycho01** [types/npm-ramda#110]
AFAICT, TS currently doesn't support this. I'd like to leave this as a place-holder for when they would start supporting this though. I think currently this is my main gripe about using Ramda with TS.

Edit: [linked issue](https://github.com/Microsoft/TypeScript/issues/12393)

**Comment by tycho01** [comment]
Update: so it looks like it should be possible; thanks to the helpful community at the TypeScript repo for helping point that out.
I'm currently still trying to figure out the details though. Anders was already helpful enough to provide a relevant example in his [PR](https://github.com/Microsoft/TypeScript/pull/12114):
```ts
function mapObject<K extends string | number, T, U>(obj: Record<K, T>, f: (x: T) => U): Record<K, U>;
```
My current confusion is w.r.t. how I might be able to reapply constructs like the `type T5 = { [P in keyof Item]: Item[P] };` so as to be able to have the result types per key be calculated based on the original type in the object for that value along with the function in/out types. Open to ideas.

**Comment by tycho01** [comment]
Made a PR for this [here](https://github.com/donnut/typescript-ramda/pull/111) now.

**Comment by jonaskello** [comment]
I think `in keyof` syntax is new in TS 2.1 so it would be required to run it?
For me that is totally OK as I want to add ReadOnlyArray that is only supported in TS 2.0 :-).

**Comment by tycho01** [comment]
Yeah, I'm under the impression it's pretty new. That said, I imagine there shouldn't be too many downsides to upgrading...

**Comment by blakeembrey** [comment]
This can be supported once `2.2.0` is released as stable. 2.1 is currently in RC, and `keyof` is currently in the nightlies.

**Comment by tycho01** [comment]
@blakeembrey: Yeah, basic support (preserving keys) is possible with `keyof`, though as it stands the full intention here (types separate by key, rather than assuming they're all homogeneous) so far isn't it seems -- note TypeScript's mhegazy couldn't quite figure this out yet [either](https://github.com/Microsoft/TypeScript/issues/12393#issuecomment-262308596), and [eventually](https://github.com/Microsoft/TypeScript/issues/12393#issuecomment-263403602) recommended following this [existing thread](https://github.com/Microsoft/TypeScript/issues/12342).
That said, it definitely seems time to jack up this TS version. :)

**Comment by blakeembrey** [comment]
Sounds great. I just found the thread because I was using `pick` and the latest nightly, and this issue covered the new `keyof` feature. I'm sure there's some other places where it'll be useful too. Looking forward to 2.2 stable myself, updating the RethinkDB definition will be lots of fun too 😄

**Comment by tycho01** [comment]
This is mostly blocked by https://github.com/Microsoft/TypeScript/issues/6606, will retry after.
