### ISSUE TITLE
Missing npm script `exec`

### ISSUE THREAD

**Issue by demurgos** [types/npm-ramda#126]
Hi,
The Travis builds are failing because it runs `npm run exec` but the `exec` script is not defined in the **package.json**.

**Comment by tycho01** [comment]
Thanks! I [commented](https://github.com/types/npm-ramda/commit/ab83e7a98cef4c16dcf3309f47c28c76673aeea6) that for now in favor of the `test` command.
So now Travis builds should fail because TS breaks many of the tests instead. :D
