### ISSUE TITLE
@types/ramda stuck at 0.0.3

### ISSUE THREAD

**Issue by myknbani** [types/npm-ramda#134]
Installing via `npm i -D @types/ramda` gives me version 0.0.3, and it lacks some methods such as pipeP.

**Comment by blakeembrey** [comment]
That's because it's published from DefinitelyTyped. Publishing from elsewhere is still waiting on https://github.com/Microsoft/types-publisher/issues/4. Feel free to comment to indicate your interest on that issue 😄

**Comment by myknbani** [comment]
Thanks @blakeembrey 

`npm install types/npm-ramda` is my temporary workaround.. 😁
