### ISSUE TITLE
Triple-slash reference to @types/ramda cannot find R

### ISSUE THREAD

**Issue by rendall** [types/npm-ramda#135]
This Typescript code produces the compilation error ```Cannot find name 'R'``` at line 3

```
/// <reference path="../../node_modules/@types/ramda/index.d.ts"/>
const greet = (first:string, last:string) => first + " " + last + "!";
const yellGreeting = R.compose(R.toUpper, greet);
const result = yellGreeting('Hello', 'World'); 
```

The type definition file is definitely referenced properly. 

Expected behavior:  
This code should produce no errors, and R should autocomplete as usual.  

Typescript version 2.1.6
'@types/ramda' version 0.0.3

**Comment by blakeembrey** [comment]
This is not the module used on NPM, you can log your issue at https://github.com/DefinitelyTyped/DefinitelyTyped instead.
