### ISSUE TITLE
Publishing to npm?

### ISSUE THREAD

**Issue by jonaskello** [types/npm-ramda#142]
If I install from npm @types/ramda I don't seem to get the typings from this repo. I'm not sure how the publish to npm process works or which version here corresponds to what is published to npm. I don't see anything under releases in this repo. Is it possible to npm install the types in this repo?

The types in this repo seems a lot better than what is currently available from npm. Specifically I want support for ReadonlyArray but this does not seem available in the version installable from npm as it uses regular arrays for the arguments.

**Comment by tycho01** [comment]
Hey. It's been suggested you can try installing using [`npm install types/npm-ramda`](https://github.com/types/npm-ramda/issues/134#issuecomment-281422302) instead. I've updated the readme to reflect that now. Thanks for bringing this up again, sorry.

**Comment by jonaskello** [comment]
Aha, thanks for the quick reply!
