### ISSUE TITLE
Released version in npm is just 0.0.3

### ISSUE THREAD

**Issue by anodynos** [types/npm-ramda#148]
Hi and thanks for these @types - they'll be really useful. 

Any chance of releasing a more current version ? 

Its 0.23.0-RC1 here while its just 0.0.3 on npm... And it feels kinda awkward having `deps: { '@types/ramda': 'git:...'} plus it hinders discoverability and usage to report bugs etc... 

Regards

**Comment by pygy** [comment]
I just `npm install types/npm-ramda --saveDev` and I have `v0.23.0-RC1` installed... I found a bug thogh (which is why I'm here scouring the issues... report incoming unless I find a related entry).

**Comment by tycho01** [comment]
Hi @anodynos,
Yeah, I only recently managed to fix the install command in the readme. I hope the new one (as stated by @pygy) will work for you.

@pygy:
Hi, feel free to create an issue for your bug. :)
I know there's quite some typing issues involving currying currently, but feel free to show an example of your problem and I'll check it out.

**Comment by blakeembrey** [comment]
@anodynos This isn't anything the authors of definitions can change unfortunately. There's been a number of these issues reported (such as https://github.com/types/npm-ramda/issues/134) and if you'd like to see this made possible, consider posting your support in https://github.com/Microsoft/types-publisher/issues/4.

**Comment by anodynos** [comment]
Thanks @blakeembrey - I upvoted it, the least I could do :-)

@pygy & @tycho01 thank guys - I didn't know of this trick - make you you highlight it!
╰─$ npi types/npm-ramda
- @types/ramda@0.0.3 node_modules/@types/ramda
someproject-API@0.1.0 /mnt/projects/Ve/someproject-API
└── @types/ramda@0.23.0-RC1  (git://github.com/types/npm-ramda.git#9502870c738f14ed387021c3125568f12a84906f)

**Comment by tycho01** [comment]
@anodynos highlighting... I wish that worked within code blocks! :D
