### ISSUE TITLE
Error TS2536: Type '0' cannot be used to index type 'T'.

### ISSUE THREAD

**Issue by pygy** [types/npm-ramda#149]
```
TypeScript error: node_modules/@types/ramda/index.d.ts(1151,45): Error TS2536: Type '0' cannot be used to index type 'T'.
```

No insights into the why, I'm new to both TypeScript and Ramda.

Edit: [here](https://github.com/types/npm-ramda/blob/87acc5ab0355b4d4c06ccf1fe5ae0f38286be789/index.d.ts#L1151)'s the offending line.

**Comment by tycho01** [comment]
Hey,
Yeah, we did get a report on that [earlier](https://github.com/types/npm-ramda/issues/129). This appeared a regression present in TS 2.1.5~2.2.0. I created a new [branch](https://github.com/types/npm-ramda/tree/TS-2.1.5-2.2.0) to accomodate the affected versions on that point.

**Comment by pygy** [comment]
I updated to TS 2.2.1, it's gone. Thanks for the help and sorry for the noise

**Comment by tycho01** [comment]
Nah, that's okay. Your issue title is friendly for others bumping into it too. :)
