### ISSUE TITLE
type Path not correctly defined

### ISSUE THREAD

**Issue by fatsu** [types/npm-ramda#150]
type Path should be (string | number)[] instead of (string | number | boolean)[].

propEq is currently defined with (string | number[]) instead of type Path

**Comment by tycho01** [comment]
Wait, propEq should be using `Prop` as it is now rather than `Path`, right?
I merged in your suggestion of kicking boolean out of Path now. Thanks for bringing that up. :)

**Comment by fatsu** [comment]
sorry, my mistake: pathEq!

**Comment by tycho01** [comment]
Thanks! :)

**Comment by fatsu** [comment]
No problem. Dank u
