### ISSUE TITLE
@types/ramda vs npm-ramda

### ISSUE THREAD

**Issue by whitecolor** [types/npm-ramda#163]
Who is actually maintaining?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ramda/index.d.ts

Maybe it is worth to combine the efforts and purth to `@types/ramda` that seems to be more consistent?

**Comment by tycho01** [comment]
Yeah, the version at DefinitelyTyped is somewhat ancient at this point; see also #134, #142, #148. Currently the recommended way of installing the types is using the command in the readme.
Maybe I should leave this open to make it more visible.

**Comment by schickling** [comment]
@tycho01 could you merge this repo to DefinitelyTyped until https://github.com/Microsoft/types-publisher/issues/4 is solved?

**Comment by tycho01** [comment]
Hi @schickling, I made one [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15912) now. Note I have no special powers here, anyone can do it. :)

**Comment by whitecolor** [comment]
@tycho01 wanted to ask how `npm-ramda` published that can be installed using `npm install types/npm-ramda` but package name is `@types/ramda`?

**Comment by tycho01** [comment]
Fair question. This was part of the reference [`package.json`](https://github.com/types/npm-quickly-copy-file/blob/master/package.json) linked in the @types [guidelines](https://github.com/types/guidelines#structure). I imagine @blakeembrey would know more. I suppose it'd relate to intended names within @types's npm super-repo (or whatever that's called).

**Comment by whitecolor** [comment]
there is `types/npm-ramda`, not `@types/npm-ramda` (the later doesn't work so you can do `npm install @types/npm-ramda`

**Comment by tycho01** [comment]
Seems you're right. Looks like Angular has the `@` in the package name as well, so not sure why they're installed with it, this repo without. I don't know the answer, so I'll have to defer this one.

**Comment by whitecolor** [comment]
Who is currently responsible the package for publication?

**Comment by tycho01** [comment]
I fear this is open-source. One guy started Ramda typings, another took over, at one point I got active, then things moved to this repo... and now I don't quite have the time as I'd hoped.
I know about these typings, Blake knows about this org... I sorta figured out how to make things work with what DefinitelyTyped expected, but then... those many errors.

**Comment by blakeembrey** [comment]
I don't understand the conversation/question, what do you mean who is responsible for "publishing the repo"? The NPM install in the README is installing from git so there's no publication involved. If you're talking about DefinitelyTyped, no one is responsible for publishing there either - that's a feature where I've been told they expect to see only drive-by contributions and not one person managing a package (it's pretty hard today to manage one package since it's all one repo and subscribing means dozens of issues/PRs a day, none related to your package). Installation from Git can use any package name (see package.json) so we've been using it as a hack to allow people to install the definitions until redirects are supported.

**Comment by whitecolor** [comment]
@blakeembrey ah) thanks `types/npm-ramda` is just a git address =) This what put me into confusion, thought npm clients support only `github:types/npm-ramda` short uri, not just `types/npm-ramda`

**Comment by blakeembrey** [comment]
No, it's not, hence saying it's a hack. But it's all that's possible today. If you're interested in building better tooling to contribute to DefinitelyTyped, I'd love to see it but in the current state I haven't seen anything to make it possible.

**Comment by ahstro** [comment]
What's the state here? Saw that `@types/ramda` just had a push a couple of days ago, so assuming it isn't "ancient" anymore? Are the two going to get merged?

**Comment by tycho01** [comment]
@ahstro expect updating that to become part of #173.

**Comment by tycho01** [comment]
WIP at #191.
