### ISSUE TITLE
prop is broken

### ISSUE THREAD

**Issue by pygy** [types/npm-ramda#167]
`prop<T>(p: Prop, obj: T): T;` can only work with recursive/circular data structures...

`prop<T, K extends keyof T>(p: K, obj: T): T[K];` was working fine for my use case, my program won't compile with the latest version of the typings.

**Comment by tycho01** [comment]
Hey, thanks for reporting this.
It looks like this commit got into the wrong branch, apparently it was more concerned with keeping compatibility with TS 1.x, which, as you pointed out, evidently came at the cost of proper inference.
Please tell me if you're still having trouble now!
