### ISSUE TITLE
Somethings seems to have broken

### ISSUE THREAD

**Issue by Ramblurr** [types/npm-ramda#168]
When I checkout the latest master into a clean folder, run npm install then npm run types, I get lots of errors.

Here is a short snippet from the top, its over 12240 lines long:

```
> @types/ramda@0.23.0-RC1 types /Users/casey/personal/src/npm-ramda
> echo testing types... && bash test.sh

testing types...
tests/test.ts: Unexpected error
  Duplicate identifier 'R'.

tests/test.ts: Unexpected error
  Cannot find namespace 'R'.

tests/test.ts: Unexpected error
  Duplicate identifier 'R'.

tests/test.ts:R.isArrayLike('a');

Expected type
  boolean
but got:
  any

tests/test.ts:R.isArrayLike([1,2,3]);

Expected type
  boolean
but got:
  any

tests/test.ts:R.isArrayLike([]);

Expected type
  boolean
but got:
  any
```

**Comment by tycho01** [comment]
I apologize. I pushed a [commit](https://github.com/types/npm-ramda/commit/117472aad2ec41d96bdb626ee5fc6ac320f434a5) to address this now.

**Comment by Ramblurr** [comment]
Great :) The index file is parsed by TS now, thanks.

```
tests/test.ts: 454 / 724 checks passed.
```

Is that expected though?

**Comment by tycho01** [comment]
Yeah, I've intentionally gone for a way of testing that'd pick out any imperfection (e.g. types inferred as `any`), and I realize there's still quite some imperfections I haven't managed to resolve.
Someone else has recently suggested [reconsidering this approach](https://github.com/types/npm-ramda/pull/165#issuecomment-291932996). I'm open to ideas.
