### ISSUE TITLE
Is there any support of composeP and pipeP?

### ISSUE THREAD

**Issue by GulinSS** [types/npm-ramda#182]
I use `"@types/ramda": "0.0.11"` and I see no `composeP` or `pipeP`. I would like to write point-free functions with promises. Just `composeP` and `pipeP` does it less pain.

**Comment by tycho01** [comment]
Hey! We've yet to push proper typings to DefinitelyTyped; could you please try using `types/npm-ramda` over `@types/ramda`?

**Comment by GulinSS** [comment]
Now it looks like
```
"devDependencies": {
    "@types/ramda": "github:types/npm-ramda"
  }
```

Now all is working! Thanks for tip about `pipeP`.

**Comment by tycho01** [comment]
No worries; glad to hear!
