### ISSUE TITLE
ts docs are not displayed in editor (IDE) helpers

### ISSUE THREAD

**Issue by whitecolor** [types/npm-ramda#202]
ts docs are not displayed in editor (IDE) helpers
![image](https://user-images.githubusercontent.com/736697/29523022-f0c9be18-86a4-11e7-869f-399ce7638ef0.png)

Because docs are placed in wrong place on interfaces/types. Docs should be placed on top interface member to be displayed:

![image](https://user-images.githubusercontent.com/736697/29522903-77b267a0-86a4-11e7-8f43-b21019bf3e12.png)

![image](https://user-images.githubusercontent.com/736697/29523007-db84126a-86a4-11e7-98d2-db7cfa0c9fb2.png)

To be displayed everywhere they acually should be placed on each interface option =) well with generated sources it is more than possible.

**Comment by ikatyang** [comment]
I'll put them on the first overload as you mentioned above, but it's impossible to put them everywhere (it's technically possible, but its size will go crazy).

**Comment by whitecolor** [comment]
Size of what? I think TS compiler can handle it without big hassle at least I would try.

I opened an issue for this thing a while a go: https://github.com/Microsoft/TypeScript/issues/17029

**Comment by ikatyang** [comment]
I mean the file size, something like this:

```ts
type remove_000 = {
  /**
   * Removes the sub-list of `list` starting at index `start` and containing
   * `count` elements. _Note that this is not destructive_: it returns a copy of
   * the list with the changes.
   * <small>No lists have been harmed in the application of this function.</small>
   *
   * @func
   * @memberOf R
   * @since v0.2.2
   * @category List
   * @sig Number -> Number -> [a] -> [a]
   * @param {Number} start The position to start removing elements
   * @param {Number} count The number of elements to remove
   * @param {Array} list The list to remove from
   * @return {Array} A new Array with `count` elements from `start` removed.
   * @example
   *
   *      R.remove(2, 3, [1,2,3,4,5,6,7,8]); //=> [1,2,6,7,8]
   */
    (start: number): remove_100;
    /**
     * Removes the sub-list of `list` starting at index `start` and containing
     * `count` elements. _Note that this is not destructive_: it returns a copy of
     * the list with the changes.
     * <small>No lists have been harmed in the application of this function.</small>
     *
     * @func
     * @memberOf R
     * @since v0.2.2
     * @category List
     * @sig Number -> Number -> [a] -> [a]
     * @param {Number} start The position to start removing elements
     * @param {Number} count The number of elements to remove
     * @param {Array} list The list to remove from
     * @return {Array} A new Array with `count` elements from `start` removed.
     * @example
     *
     *      R.remove(2, 3, [1,2,3,4,5,6,7,8]); //=> [1,2,6,7,8]
     */
    (_start: PH, counter: number): remove_010;
    /**
     * Removes the sub-list of `list` starting at index `start` and containing
     * `count` elements. _Note that this is not destructive_: it returns a copy of
     * the list with the changes.
     * <small>No lists have been harmed in the application of this function.</small>
     *
     * @func
     * @memberOf R
     * @since v0.2.2
     * @category List
     * @sig Number -> Number -> [a] -> [a]
     * @param {Number} start The position to start removing elements
     * @param {Number} count The number of elements to remove
     * @param {Array} list The list to remove from
     * @return {Array} A new Array with `count` elements from `start` removed.
     * @example
     *
     *      R.remove(2, 3, [1,2,3,4,5,6,7,8]); //=> [1,2,6,7,8]
     */
    (start: number, counter: number): remove_110;
    /**
     * Removes the sub-list of `list` starting at index `start` and containing
     * `count` elements. _Note that this is not destructive_: it returns a copy of
     * the list with the changes.
     * <small>No lists have been harmed in the application of this function.</small>
     *
     * @func
     * @memberOf R
     * @since v0.2.2
     * @category List
     * @sig Number -> Number -> [a] -> [a]
     * @param {Number} start The position to start removing elements
     * @param {Number} count The number of elements to remove
     * @param {Array} list The list to remove from
     * @return {Array} A new Array with `count` elements from `start` removed.
     * @example
     *
     *      R.remove(2, 3, [1,2,3,4,5,6,7,8]); //=> [1,2,6,7,8]
     */
    <T>(_start: PH, _counter: PH, list: T[]): remove_001<T>;
   // ...
}
```

---

It's currently 1.3MB for npm-ramda (dist) types, I can't imagine how it will be if we add docs everywhere.
![image](https://user-images.githubusercontent.com/8341033/29524118-8eb64ecc-86c1-11e7-89a6-73b46117362c.png)

**Comment by tycho01** [comment]
I'm somehow reminded of [this quote](https://github.com/Microsoft/TypeScript/issues/5453#issuecomment-220881912) that overloads are 'a decent workaround' to proper language features. Yeah, it's pretty unfortunate; hoping I can figure that 5453 out for starters.

**Comment by whitecolor** [comment]
> It's currently 1.3MB for npm-ramda (dist) types, I can't imagine how it will be if we add docs everywhere.

Why not try. No all methods contain som many overloads. Size on disk in not a big problem, this are not production code anyway.

**Comment by tycho01** [comment]
Man, that's gonna be fun for e.g. `R.path`. I suppose git/npm probably send content over the wire gzipped though? That way download size might actually be somewhat under control.

**Comment by ikatyang** [comment]
It's almost 3x size for docs everywhere version.

![image](https://user-images.githubusercontent.com/8341033/29526345-04404caa-86c8-11e7-9751-2d6a9d35e3c9.png)

---

I think we won't support that version officially, but if you're interested in docs everywhere, just modify this line 

https://github.com/types/npm-ramda/blob/3ea38105e465cf20c12e599ad5e5786dd08dc08b/tasks/utils/generate-file-content.ts#L99

into 

```ts
target_overloads.forEach(x => bind_jsdoc(filename, x));
```

then `yarn run build`, you'll see the definitions in `ramda/dist` folder.

**Comment by ikatyang** [comment]
Oops, it's not only 3x size, that's just for adding jsdocs for first-overload (e.g. `remove_000`).

**Comment by whitecolor** [comment]
x3 not a big deal really for convenience and if performance doesn't suffer.

I think it could be published in a separate branch in git, and as the separate tag in NPM.

**Comment by ikatyang** [comment]
Sorry, my fault, this is the actual size (5x).

![image](https://user-images.githubusercontent.com/8341033/29527399-5a691aaa-86cb-11e7-89bb-77d0ec75088f.png)

I'm sure it'll affect performance, but I don't know how big it will be.

For publishing to the separate branch, I don't think it's a good idea since we won't support it officially unless there's a solution to not increase so many size. (one of our goal is to decrease the size as much as possible)

You can fork it and build the docs everywhere version:

https://github.com/types/npm-ramda/blob/9ba9a5beb47f5872bf921bc2127d440ee6fc3086/tasks/utils/generate-file-content.ts#L78

```ts
function bind_member_jsdoc() {
    members.forEach(member => {
      switch (member.kind) {
        case dts.ElementKind.TypeDeclaration:
          if (member.type!.kind === dts.ElementKind.ObjectType) {
            const target_overloads = (member.type as dts.IObjectType).members!;
            target_overloads.forEach(x => bind_jsdoc(filename, x));
          }
          break;
        case dts.ElementKind.FunctionDeclaration:
        case dts.ElementKind.VariableDeclaration:
          bind_jsdoc(filename, member);
          break;
        default:
          // do nothing;
          break;
      }
    });
  }
```

---

And we have no control for the NPM package.
