### ISSUE TITLE
pluck typings issue

### ISSUE THREAD

**Issue by bloadvenro** [types/npm-ramda#253]
Hello!

I have the latest typings (installed as `yarn add --dev types/npm-ramda#dist`).
 
My code looks approximately like this:

```
R.pluck('value',
  R.pick(['a'])({
    'a': { value: 'some_value' },
    'b': { value: 'some_value' },
  }) // = {'a': {value: 'some_value'}}
)
```

Typescript throws:
```
TS2345:
Argument of type 'Pick<{ 'a': { value: string; }; 'b': { value: string; }; }, "a">' is not assignable to parameter of type 'List<any>'.

Type 'Pick<{ 'a': { value: string; }; 'b': { value: string; }; }, "a">' is not assignable to type 'ArrayLike<any>'.

Property 'length' is missing in type 'Pick<{ 'a': { value: string; }; 'b': { value: string; }; }, "a">'.
```

First of all such use case is valid accordingly to documentation:
```
R.pluck('a')([{a: 1}, {a: 2}]); //=> [1, 2]
R.pluck(0)([[1, 2], [3, 4]]);   //=> [1, 3]
R.pluck('val', {a: {val: 3}, b: {val: 5}}); // << My case. Typescript also throws here. 
```
Possibly I misunderstand something, but from my point of view, this looks like missing typings for dictionary-like argument type. Thank you!

**Comment by bloadvenro** [comment]
First of all thank you for working on this project!

Pull request added object kind, but curried version still references to the `List` type version:

```
R.pluck('val', {a: {val: 3}, b: {val: 'x'}}) // OK
R.pluck('val')({a: {val: 3}, b: {val: 'x'}}) // Error

'Argument of type '{ a: { val: number; }; b: { val: string; }; }' is not assignable to parameter of type 'List<Record<"val", {}>>'.
  Object literal may only specify known properties, and 'a' does not exist in type 'List<Record<"val", {}>>'.'
```

Thank you!

**Comment by ikatyang** [comment]
As I mentioned in https://github.com/types/npm-ramda/pull/254#issuecomment-333033130, this issue is about the missing feature in the type generator. I'd like to fix it but I found some problems that I have no idea how to solve, see https://github.com/ikatyang/dts-element-fp/issues/56#issuecomment-334911254.
