### ISSUE TITLE
Type for Merge<T, U> overwrites requried props with unrequired

### ISSUE THREAD

**Issue by ahstro** [types/npm-ramda#266]
If I have a type `Person` and try to merge in a `Partial<Person>`, the output type is not `Person` as logically would follow, but `Partial<Person>` because all the optional properties overwrite the required ones, causing an error like this:

```
Type 'Merge<Person, Partial<Person>>' is not assignable to type 'Person'.
Types of property 'name' are incompatible.
Type 'string | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'.
```

**Comment by ikatyang** [comment]
The optional property in TS is allowed to assign `undefined`, though it looks strange in your case, but it did has the possibility of overwriting the required property with `undefined`.

```ts
interface Person {
  name: string;
}

const person: Partial<Person> = { name: undefined }; // valid
```

**Comment by ahstro** [comment]
Oh, of course, thanks for clearing that up

**Comment by tycho01** [comment]
I sympathize with the intent here, and recall there was an issue over at TypeScript about this behavior... I can't find it atm though. For the time being, might a manual cast to `Person` help address the issue for you @ahstro?

**Comment by ahstro** [comment]
That is what I resolved to doing, thanks @tycho01 :)
