### ISSUE TITLE
Use with tsconfig paths

### ISSUE THREAD

**Issue by aluanhaddad** [types/npm-ramda#271]
First of all thank you for this package!

I think it might be helpful to include the documentation on settings up the necessary `"paths"` in `tsconfig.json` for this package. This would be useful for those working with toolchains that are not centered around npm or Yarn.

I am using the awesome support for partial imports enabled by this types package, so I set up the following
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths" : {
       "ramda/src/*": [
         "location-of-types/npm-ramda-package/src/*"
       ]
     }
  }
}
```

For working with the full package one would write
```json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths" : {
       "ramda": [
         "location-of-types/npm-ramda-package/index"
       ]
     }
  }
}
```
Thank you.

**Comment by tycho01** [comment]
Thanks! Nice to see you around here. :)
Added it in now, but if you'd like to change stuff feel free to submit PRs as well!

**Comment by aluanhaddad** [comment]
@tycho01 thanks so much. I started using ramda this week. I am really enjoying it.

**Comment by tycho01** [comment]
Glad to hear you like it! I'll concede the typing aren't as seamless as they should be yet (pointfree notation still needs more manual annotations than I'd like), but hopefully we'll get there!
