### ISSUE TITLE
Type errors for Ramda cookbook methods `mapKeys` and `renameBy`

### ISSUE THREAD

**Issue by mtpultz** [types/npm-ramda#273]
I'm trying to figure out what the proper typings are for the [Ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#map-keys-of-an-object) method `mapKeys` so it will transpile without throwing an error due to typings on `fn` argument of the anonymous function.

**Example**

```js
    import * as R from 'ramda';
    
    export const mapKeys = R.curry(
      (fn: ???, obj: { [k: string]: any } | { [k: number]: any }) =>
        R.fromPairs(
          R.map(
            R.adjust(fn, 0), // <--- Error: tried typings for `adjust`
            R.toPairs(obj) // Fixed by referencing typings of `toPairs`
          )
        )
    );
```

**Error**

Error is on `fn`:
> Argument of type '{}' is not assignable to parameter of type '(a: string) => string'. Type '{}' provides no match for the signature '(a: string): string'.

**Description**

As you would expect you can solve similar issues like with `obj` by referencing the `toPairs` typings of `{ [k: string]: any } | { [k: number]: any }`, but I tried using the `adjust` typings for `fn` of `(a: any) => any` with no luck.

A similar typings error occurs for another [Ramda cookbook](https://github.com/ramda/ramda/wiki/Cookbook#map-keys-of-an-object) method `renameBy` that also uses `adjust`, so I thought maybe this was a typings issue with `adjust`, but the example below works.

```
R.adjust((a: any): any => {
  return 2;
}, 2);
```

**Comment by tycho01** [comment]
Typings have trouble with generics, yeah. I tried reminding them this was still an issue at https://github.com/Microsoft/TypeScript/pull/16072#issuecomment-310996281.

Anyway, glad you liked `renameKeys`!
If typings are having trouble though, you could try it with a less point-free version as well, e.g. `(arr: [string, any]) => [fn(arr[0]), arr[1]]` over the `adjust` line. I think `fn` should just be `(s: string) => string` type right?

**Comment by mtpultz** [comment]
Thanks for the reply @tycho01.  

Definitely, find `renameKeys` quite useful since it is declarative and self-documenting at least when I'm using native ES6, so thanks if that's your addition to the Ramda cookbook :)

Yah `fn` should be `(s: string) => string`, but using that just moves the error down into `R.map` and my TypeScript isn't very strong yet so I'm really not sure which error is the culprit vs red herring.

> Argument of type 'string[][]' is not assignable to parameter of type 'KeyValuePair<number, string | string[]>[]'. Type 'string[]' is not assignable to type 'KeyValuePair<number, string | string[]>'. Property '0' is missing in type 'string[]'.

![image](https://user-images.githubusercontent.com/599498/31305634-41f02954-aaf3-11e7-80c3-79ab71bf69b1.png)

**Comment by tycho01** [comment]
Oh, that makes sense. So what it's saying is if `fn` is `(s: string) => string`, that wouldn't match `number` keys. Perhaps changing the function to accept those would do it?

**Comment by mtpultz** [comment]
Hi @tycho01, thanks for the help.  I tried setting `fn` to accept number keys as well, and a bunch of other variations using the type definitions for map and adjust, but each variation just jumps back and forth between an issue with `R.map` or `fn` regarding their typings.

I think this is probably the most confusing thing with TypeScript which is impeding our full adoption of it into Node projects, and in this particular case means not using Ramda in Angular or Node unless developed using native ES6/7/Next.  I almost can't imagine living without type safety, but the time spent doing this is overwhelming since it isn't like a "normal" bug you can just track down.

**Comment by tycho01** [comment]
@mtpultz: I sympathize. Particularly in functional programming, TypeScript unfortunately may still feel like more of a bolt-on type system than an innately typed language.

/cc @ikatyang: his issue appears to be that `fromPairs` rejects the input here as the binary tuple indices `0` / `1` obtained from `toPairs` go lost in the `map` operation, even if the operation (`adjust` here) is swapped out for `identity`. That's admittedly unfortunate, and makes the function a bit harder to use type-wise.

I can see the intentions w.r.t. type safety though. The most solution seems type-level heterogeneous `map` -- guess I should continue on https://github.com/Microsoft/TypeScript/pull/17961.

A short-term solution should involve a cast I guess...

**Comment by mtpultz** [comment]
Thanks for fixing that issue.  I was looking at the committed fix out of interest and that is definitely outside my realm of understanding.  Is it possible to consume the update on npm, or is Microsoft/TypeScript#17884 blocking?

**Comment by ikatyang** [comment]
@mtpultz 

We're trying to send PRs to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), but unfortunately it's blocked, see #233.

**Comment by raine** [comment]
```ts
import * as R from 'ramda'

export const mapKeys = R.curry(
  (fn: (key: string) => string, obj: { [k: string]: any } | { [k: number]: any }) =>
    R.fromPairs(
      R.map(
        R.adjust<0, [string, any]>(fn, 0),
        R.toPairs(obj)
      )
    )
)
```

So should this work?

Getting `src/map-keys.ts(7,9): error TS2558: Expected 1 type arguments, but got 2.`

**Comment by ikatyang** [comment]
@raine Similar to #377, see https://github.com/types/npm-ramda/issues/377#issuecomment-359676549.
