### ISSUE TITLE
R.head doesn't type well

### ISSUE THREAD

**Issue by whitecolor** [types/npm-ramda#308]
I belive This should be just enough for `R.head` for correct typings
```
interface Head {
  /**
 * Returns the first element in a list.
 * In some libraries this function is named `first`.
 * Takes tuple.
 */
 <T0, T1>(list: [T0, T1]): T0;
}
```
having `<T>(list: T[]): T;` beaks typings:
![image](https://user-images.githubusercontent.com/736697/32141947-7a15c8b2-bcae-11e7-861f-ae000f0f5bcb.png)

**Comment by ikatyang** [comment]
I'm not sure how did you get there, it works fine to me. You may have to update your types.

https://github.com/types/npm-ramda/blob/d6b0f2c704de081371e08a818eb32b424163b7af/templates/head.d.ts#L4

![image](https://user-images.githubusercontent.com/8341033/32142707-af20c68c-bcd7-11e7-8bc2-74c3a3f6b95f.png)

**Comment by whitecolor** [comment]
Oh, right, was old version in the project.
