### ISSUE TITLE
map intended typings

### ISSUE THREAD

**Issue by FlattestWhite** [types/npm-ramda#377]
With R.map typings,

Currently, it seems to be

`map<In, Out>(fn: MapFunction<In, Out>, list: ReadonlyArray<Out>): Out[]`

Is this the intended typing?

Shouldn't it be
`map<In, Out>(fn: MapFunction<In, Out>, list: ReadonlyArray<In>): Out[]`

Am I missing something here?

**Comment by ikatyang** [comment]
Hi, it seems you're not using our types, see [usage](https://github.com/types/npm-ramda#usage).

https://github.com/types/npm-ramda/blob/e59375898428573ca5d1491e87e3cc02c89cc1d1/templates/map.d.ts#L3
