### ISSUE TITLE
Partition is not working on objects

### ISSUE THREAD

**Issue by jcristovao** [types/npm-ramda#387]
Hey,

I had quite some time ago [added support for objects on R.partition](https://github.com/types/npm-ramda/pull/99), but this seems to have been dropped for some reason.

Is there any way to get this back?
Thanks

**Comment by ikatyang** [comment]
Can you share some example code? The [`R.partition` for objects](https://github.com/types/npm-ramda/blob/master/templates/partition.d.ts#L4-L7) is still available.

**Comment by jcristovao** [comment]
Ok, mea culpa... I thought when we installed `@types/ramda` these get installed, but its a different version. The ones here work great, thanks :)

Still, any chance of making these the 'officials'?

**Comment by tycho01** [comment]
@jcristovao #191
