### ISSUE TITLE
tsc hangs when npm-ramda#dist is installed

### ISSUE THREAD

**Issue by jirutka** [types/npm-ramda#402]
tsc allocates around 1.5 GiB RAM and does not finish even in 30 sec. I've tried both typescript 2.9.2 and 3.1.0-dev.20180721 (current `@next`). It even doesn't matter if ramda is actually imported and used in the code.

Command:
```sh
npx tsc -p .
```

package.json:
```json
{
  "name": "foo",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@types/node": "^10.5.2",
    "@types/ramda": "types/npm-ramda#dist",
    "typescript": "^2.9.2"
  }
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es6",
    "strict": true,
    "strictFunctionTypes": false,
    "lib": [
      "es2017"
    ]
  },
  "include": [
    "src/**/*.ts"
  ]
}
```

* node v8.11.3
* Linux 4.12.14 (openSUSE)
* x86_64

**Comment by treybrisbane** [comment]
I also have this problem

**Comment by ikatyang** [comment]
Could you remove these `"6"` ~ `"29"` item in `NumberStringMap` and see if it still hung?

https://github.com/types/npm-ramda/blob/6df524d388d183d9ce79fe58a50152eff4663a74/src/%24operation.d.ts#L18-L52

**Comment by jirutka** [comment]
I've tried that, still hung.
