### ISSUE TITLE
Optional arguments not registered as such in partial returns

### ISSUE THREAD

**Issue by mplanchard** [types/npm-ramda#408]
Hi there!

I'm new to Typescript, so I apologize if this is a Typescript issue and not an `npm-ramda` issue.

When using `partial` on a function with some required and a final optional argument, the type registered on the resulting function does not preserve the optional state of the original argument.

Example:

```ts
// const _Foo: (a: string, b: string, c?: any) => void
const _Foo = (a: string, b: string, c: string = 'c') => { console.log(a, b, c) };

// const Foo: (x2: string) => void
const Foo = R.partial(_Foo, ['a', 'b'])

Foo()  // [ts] Expected 1 arguments, but got 0.
// a b c
```

the result is the same if you set the variable to optional with the `?` syntax and do not provide a default value:

```ts
// const _Foo: (a: string, b: string, c?: string | null | undefined) => void
const _Foo = (a: string, b: string, c?: string|null|undefined) => { console.log(a, b, c) };

// const Foo: (x2: string | null | undefined) => void
const Foo = R.partial(_Foo, ['a', 'b'])

Foo()  //  [ts] Expected 1 arguments, but got 0.
// a b undefined
```

It's also definitely possible I'm doing something wrong. Thanks in advance!

**Comment by ikatyang** [comment]
The type inference is currently a TS limitation that it can not distinguish missing and undefined (Microsoft/TypeScript#13195), and the runtime difference is caused by Microsoft/TypeScript#23251 (`R.partial`'s implementation is based on `Function#length`).
