### ISSUE TITLE
TS 3.0 compatibility broken in last dist

### ISSUE THREAD

**Issue by jethrolarson** [types/npm-ramda#410]
npm-ramda was working with TS 3.0.1 until this change:
https://github.com/types/npm-ramda/commit/4dff37c10f771d60850dd04fa82ce0bf5a2b1d68

**Comment by lukasbash** [comment]
Can reproduce in latest dist.
I guess some information about the error could be useful:
`ERROR in [wc] ./node_modules/@types/ramda/src/$operation.d.ts:11:31
    TS2536: Type 'T extends object ? U extends object ? 0 : 1 : 1' cannot be used to index type '{ "0": Pick<T, Exclude<keyof T, keyof U>> & Pick<U, Exclude<keyof U, keyof T>> & { [K in Extract<...'.`
