### ISSUE TITLE
pathOr requires two generics, when one makes more sense

### ISSUE THREAD

**Issue by ipanasenko** [types/npm-ramda#416]
Hey guys.

I'm using `pathOr` like this:

```ts
type TSomeProp = { cc: number; };
type TItem = {
  aaa: TSomeProp[];
};
const item: TItem = {
  ...
};

pathOr<TSomeProp[], TSomeProp[]>([], ['aaa'], item);
```

It seems that I always need to specify two generics, even if I want default to be the same type as what I get on that path.

Do you think we can make second generic optional?

BTW, I think this also applies to `propOr`

**Comment by ikatyang** [comment]
Unfortunately, it'll cause an unexpected inference for currying due to their type parameter dependencies:

```diff
-R.pathOr('N/A')(['a', 'b'], { a: { b: 2 } }) //=> string | {}
+R.pathOr('N/A')(['a', 'b'], { a: { b: 2 } }) //=> string
```

**Comment by ipanasenko** [comment]
Got you, thanks!
