### ISSUE TITLE
R.includes is not include here.

### ISSUE THREAD

**Issue by NathanLi** [types/npm-ramda#422]
https://github.com/ramda/ramda/blob/v0.26.1/source/includes.js

**Comment by robations** [comment]
@NathanLi does this now exist? Because I don't see it either...

Context for anyone looking at this: `contains` has been renamed `includes` to bring it more in line with native Array methods. `contains` is deprecated since 0.26.

**Comment by NathanLi** [comment]
This types is typing compatible with ramda@0.25.0 and typescript@~2.9.2.   So we can't see it here.

**Comment by robations** [comment]
Ah, I see :) Looks like quite a few [changes in 0.26](https://github.com/ramda/ramda/issues/2702).
