### ISSUE TITLE
npm-ramda motivation

### ISSUE THREAD

**Issue by hitmands** [types/npm-ramda#429]
Hi, 
there's already [`@types/ramda`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/ramda), what is the reason to prefer `npm-ramda`?
would it be worthy to have a brief explanation on the Readme?

**Comment by wclr** [comment]
@ikatyang also is there a motivation to make some updates/fixes for the latest TS version? =)

**Comment by KiaraGrouwstra** [comment]
tl;dr [I'm to be blamed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25430#issuecomment-386436160).

**Comment by KiaraGrouwstra** [comment]
also see https://github.com/types/npm-ramda/issues/78#issuecomment-471210078

**Comment by KiaraGrouwstra** [comment]
might the DT typings be preferable now with the type-level curry there? if so then maybe we should say that in the readme here yeah...
